name: float_column
description: Flutter FloatColumn widget for building a vertical column of widgets and text where the text wraps around floated widgets, similar to how CSS float works.
version: 2.1.8
repository: https://github.com/ronjb/float_column

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints_plus: ^3.1.0
  flutter_test:
    sdk: flutter
